---
name: POE-Component-CPAN-SQLite-Info
version: 0.07
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: |-
  non-blocking wrapper
  around L<CPAN::SQLite::Info> with file fetching abilities.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CPAN::SQLite::Info: 0.18
  Carp: 1.04
  File::Spec: 3.2501
  LWP::UserAgent: 2.036
  POE: 0.9999
  POE::Filter::Line: 1.192
  POE::Filter::Reference: 1.2187
  POE::Wheel::Run: 1.2179
build_requires:
  Test::More: 0
provides:
  POE::Component::CPAN::SQLite::Info:
    file: lib/POE/Component/CPAN/SQLite/Info.pm
    version: 0.07
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
