--- #YAML:1.0
name:                POE-Component-CPAN-SQLite-Info
version:             0.05
abstract:            non-blocking wrapper
license:             ~
author:              
    - Zoffix Znet <zoffix@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          1.04
    CPAN::SQLite::Info:            0.18
    File::Spec:                    3.2501
    LWP::UserAgent:                2.036
    POE:                           0.9999
    POE::Filter::Line:             1.192
    POE::Filter::Reference:        1.2187
    POE::Wheel::Run:               1.2179
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
